"""add_markdown_lint_rules_table

Revision ID: 0b2fbc882ef4
Revises: eca1483c944a
Create Date: 2025-09-17 23:31:46.319943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b2fbc882ef4'
down_revision: Union[str, Sequence[str], None] = 'eca1483c944a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
