"""create_markdown_lint_rules_table_proper

Revision ID: 5417dceecb6e
Revises: 0b2fbc882ef4
Create Date: 2025-09-17 23:32:04.016305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5417dceecb6e'
down_revision: Union[str, Sequence[str], None] = '0b2fbc882ef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'markdown_lint_rules',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('scope', sa.String(length=20), nullable=False),
        sa.Column('scope_id', sa.Integer(), nullable=True),
        sa.Column('scope_value', sa.String(length=500), nullable=True),
        sa.Column('rules', sa.JSON(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'scope', 'scope_id', 'scope_value', name='uq_lint_rule_scope')
    )
    op.create_index(op.f('ix_markdown_lint_rules_scope'), 'markdown_lint_rules', ['scope'], unique=False)
    op.create_index(op.f('ix_markdown_lint_rules_scope_id'), 'markdown_lint_rules', ['scope_id'], unique=False)
    op.create_index(op.f('ix_markdown_lint_rules_scope_value'), 'markdown_lint_rules', ['scope_value'], unique=False)
    op.create_index(op.f('ix_markdown_lint_rules_user_id'), 'markdown_lint_rules', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_markdown_lint_rules_user_id'), table_name='markdown_lint_rules')
    op.drop_index(op.f('ix_markdown_lint_rules_scope_value'), table_name='markdown_lint_rules')
    op.drop_index(op.f('ix_markdown_lint_rules_scope_id'), table_name='markdown_lint_rules')
    op.drop_index(op.f('ix_markdown_lint_rules_scope'), table_name='markdown_lint_rules')
    op.drop_table('markdown_lint_rules')
    # ### end Alembic commands ###
