"""add_editor_width_percentage_to_users

Revision ID: 60f546c19fc4
Revises: 63b273275d1f
Create Date: 2025-09-23 07:53:33.158450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60f546c19fc4'
down_revision: Union[str, Sequence[str], None] = '63b273275d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with default value to handle existing records
    op.add_column('users', sa.Column('editor_width_percentage', sa.Integer(), nullable=False, server_default='40'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'editor_width_percentage')
    # ### end Alembic commands ###
