"""Add image_metadata field to documents

Revision ID: 74f38b18377a
Revises: 25784be2625f
Create Date: 2025-10-28 08:46:30.647700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74f38b18377a'
down_revision: Union[str, Sequence[str], None] = '25784be2625f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('image_metadata', sa.JSON(), nullable=True, comment='Image-specific metadata including crop information per document instance'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'image_metadata')
    # ### end Alembic commands ###
