"""add_document_embeddings_table

Revision ID: 759207316785
Revises: ddcf7fb1764b
Create Date: 2026-03-13 23:53:07.603878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '759207316785'
down_revision: Union[str, Sequence[str], None] = 'ddcf7fb1764b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension (idempotent — safe to run multiple times)
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index('ix_document_embeddings_document_id', 'document_embeddings', ['document_id'], unique=False)
    op.create_index('ix_document_embeddings_user_id', 'document_embeddings', ['user_id'], unique=False)
    # HNSW index for fast approximate nearest-neighbor cosine similarity search
    op.execute(
        "CREATE INDEX ix_document_embeddings_hnsw ON document_embeddings "
        "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )
    op.drop_index(op.f('idx_public_event_ledger_consumer_group'), table_name='event_ledger')
    op.drop_index(op.f('idx_public_event_ledger_type_processed'), table_name='event_ledger')
    op.drop_table('event_ledger')
    # Use IF NOT EXISTS — this index may already exist on databases bootstrapped
    # via create_tables() before Alembic was introduced.
    op.execute("CREATE INDEX IF NOT EXISTS ix_github_repository_selections_id ON github_repository_selections (id)")
    op.drop_index(op.f('idx_users_identity_user_id'), table_name='users')
    op.drop_column('users', 'identity_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('identity_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_users_identity_user_id'), 'users', ['identity_user_id'], unique=False)
    op.execute("DROP INDEX IF EXISTS ix_github_repository_selections_id")
    op.create_table('event_ledger',
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('consumer_group', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('processing_result', sa.VARCHAR(length=50), server_default=sa.text("'success'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("processing_result::text = ANY (ARRAY['success'::character varying, 'failure'::character varying, 'skipped'::character varying]::text[])", name=op.f('event_ledger_result_check')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('event_ledger_pkey'))
    )
    op.create_index(op.f('idx_public_event_ledger_type_processed'), 'event_ledger', ['event_type', 'processed_at'], unique=False)
    op.create_index(op.f('idx_public_event_ledger_consumer_group'), 'event_ledger', ['consumer_group', 'processed_at'], unique=False)
    op.drop_index('ix_document_embeddings_user_id', table_name='document_embeddings')
    op.drop_index('ix_document_embeddings_document_id', table_name='document_embeddings')
    op.execute("DROP INDEX IF EXISTS ix_document_embeddings_hnsw")
    op.drop_table('document_embeddings')
    # ### end Alembic commands ###
