"""Add last_opened_at to documents

Revision ID: 857f921cccd9
Revises: 8e053a703637
Create Date: 2025-09-10 23:40:38.505982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '857f921cccd9'
down_revision: Union[str, Sequence[str], None] = '8e053a703637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_documents_last_opened_at'), 'documents', ['last_opened_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_last_opened_at'), table_name='documents')
    op.drop_column('documents', 'last_opened_at')
    # ### end Alembic commands ###
