"""Remove category field from documents and make category_id not null

Revision ID: e8ff44c7c77d
Revises: 8c02283bf88e
Create Date: 2025-08-22 02:50:11.746199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ff44c7c77d'
down_revision: Union[str, Sequence[str], None] = '8c02283bf88e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # First, ensure all documents have a valid category_id before making it NOT NULL
    # This should already be done by our earlier database fixes, but let's be safe

    # Make category_id NOT NULL
    op.alter_column('documents', 'category_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)

    # Drop the old category string field index
    op.drop_index(op.f('ix_documents_category'), table_name='documents')

    # Update foreign key constraint to RESTRICT instead of SET NULL
    op.drop_constraint(op.f('fk_documents_category_id'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'categories', ['category_id'], ['id'], ondelete='RESTRICT')

    # Finally, drop the redundant category string column
    op.drop_column('documents', 'category')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documents_category_id'), 'documents', 'categories',
                          ['category_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_documents_category'), 'documents', ['category'], unique=False)
    op.alter_column('documents', 'category_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
