# generated by datamodel-codegen:
#   filename:  identity.user.v1/UserDisabled.json
#   timestamp: 2025-11-23T06:26:27+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, EmailStr, Extra, Field


class Reason(Enum):
    """
    Reason for account disabling
    """

    admin_action = 'admin_action'
    self_deletion = 'self_deletion'
    security_violation = 'security_violation'
    policy_violation = 'policy_violation'


class UserDisabledEvent(BaseModel):
    """
    Event emitted when a user account is disabled
    """

    class Config:
        extra = Extra.forbid

    user_id: UUID = Field(..., description='Unique identifier for the user')
    tenant_id: UUID = Field(..., description='Tenant identifier')
    email: EmailStr = Field(..., description="User's email address")
    display_name: Optional[str] = Field(None, description="User's display name")
    disabled_at: datetime = Field(..., description='When the user was disabled')
    disabled_by: UUID = Field(
        ..., description='ID of user/admin who disabled this account'
    )
    reason: Reason = Field(..., description='Reason for account disabling')
