# generated by datamodel-codegen:
#   filename:  identity.user.v1/UserUpdated.json
#   timestamp: 2025-11-23T06:26:27+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, EmailStr, Extra, Field


class Status(Enum):
    """
    User account status
    """

    active = 'active'
    disabled = 'disabled'


class UserUpdatedEvent(BaseModel):
    """
    Event emitted when a user is updated
    """

    class Config:
        extra = Extra.forbid

    user_id: UUID = Field(..., description='Unique identifier for the user')
    tenant_id: UUID = Field(..., description='Tenant identifier')
    email: EmailStr = Field(..., description="User's email address")
    display_name: Optional[str] = Field(..., description="User's display name")
    first_name: Optional[str] = Field(None, description="User's first name")
    last_name: Optional[str] = Field(None, description="User's last name")
    status: Status = Field(..., description='User account status')
    is_verified: Optional[bool] = Field(
        None, description='Whether user email is verified'
    )
    is_admin: Optional[bool] = Field(
        None, description='Whether user has admin privileges'
    )
    mfa_enabled: Optional[bool] = Field(
        None, description='Whether MFA is enabled for user'
    )
    updated_at: datetime = Field(..., description='When the user was last updated')
    changed_fields: list[str] = Field(
        ..., description='List of fields that were changed in this update'
    )
