# generated by datamodel-codegen:
#   filename:  envelope.v1.json
#   timestamp: 2025-11-23T06:26:27+00:00

from __future__ import annotations

from datetime import datetime
from typing import Any, Optional
from uuid import UUID

from pydantic import BaseModel, Extra, Field


class EventEnvelopeV1(BaseModel):
    """
    Standardized envelope for all domain events
    """

    class Config:
        extra = Extra.forbid

    event_id: UUID = Field(..., description='Unique identifier for this event')
    event_type: str = Field(
        ..., description='Type of event (e.g., UserCreated, UserUpdated)'
    )
    topic: str = Field(..., description='Redis stream topic (e.g., identity.user.v1)')
    schema_version: int = Field(
        ..., description='Schema version for compatibility', ge=1
    )
    occurred_at: datetime = Field(
        ..., description='ISO 8601 timestamp when event occurred'
    )
    tenant_id: UUID = Field(..., description='Tenant identifier for multi-tenancy')
    aggregate_id: UUID = Field(
        ..., description='ID of the aggregate that generated this event'
    )
    aggregate_type: Optional[str] = Field(
        'user', description='Type of aggregate (e.g., user, document)'
    )
    correlation_id: Optional[UUID] = Field(
        None, description='Optional correlation ID for request tracing'
    )
    payload: dict[str, Any] = Field(..., description='Event-specific payload data')
