"""Drop icon_count column from icon_packs

Revision ID: 08b221d47b00
Revises: 78bcb483103e
Create Date: 2025-09-06 01:45:58.652374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b221d47b00'
down_revision: Union[str, Sequence[str], None] = '78bcb483103e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column, then immediately drop it (this migration was created to clean up a temporary column)
    op.add_column(
        'icon_packs',
        sa.Column('icon_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False)
    )
    op.drop_column('icon_packs', 'icon_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'icon_packs',
        sa.Column('icon_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
