"""add password reset fields to users

Revision ID: 0cc093a64efe
Revises: 8c240984c488
Create Date: 2025-07-03 12:17:24.914843

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0cc093a64efe"
down_revision: Union[str, Sequence[str], None] = "8c240984c488"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("reset_token", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users", sa.Column("reset_token_expires", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "reset_token_expires")
    op.drop_column("users", "reset_token")
    # ### end Alembic commands ###
