"""Initial migration with all models

Revision ID: 3e8b51b52200
Revises: 
Create Date: 2025-08-12 09:35:09.051903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e8b51b52200'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_recovery_id'), table_name='document_recovery')
    op.drop_table('document_recovery')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_recovery',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('recovered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('collision', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('document_recovery_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('document_recovery_pkey'))
    )
    op.create_index(op.f('ix_document_recovery_id'), 'document_recovery', ['id'], unique=False)
    # ### end Alembic commands ###
