"""Add last_sync field to github_account table

Revision ID: 4ce8da2733ee
Revises: 86770e62ceb7
Create Date: 2025-08-27 04:24:24.305227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce8da2733ee'
down_revision: Union[str, Sequence[str], None] = '86770e62ceb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_accounts', sa.Column('last_sync', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_accounts', 'last_sync')
    # ### end Alembic commands ###
