"""Add Phase 2 GitHub fields

Revision ID: 5577969e037f
Revises: 4ce8da2733ee
Create Date: 2025-08-27 07:44:54.432483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5577969e037f'
down_revision: Union[str, Sequence[str], None] = '4ce8da2733ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('github_branch', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('local_sha', sa.String(length=40), nullable=True))
    op.add_column('documents', sa.Column('github_commit_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'github_commit_message')
    op.drop_column('documents', 'local_sha')
    op.drop_column('documents', 'github_branch')
    # ### end Alembic commands ###
