"""Convert full_key to computed hybrid property

Revision ID: 63b273275d1f
Revises: 4a00a3cac078
Create Date: 2025-09-22 14:29:40.830593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63b273275d1f'
down_revision: Union[str, Sequence[str], None] = '4a00a3cac078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('github_repository_selections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('github_repository_selections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_github_repository_selections_id'), 'github_repository_selections', ['id'], unique=False)
    op.alter_column('github_sync_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('github_sync_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_icon_metadata_full_key'), table_name='icon_metadata')
    op.drop_constraint(op.f('uq_icon_full_key'), 'icon_metadata', type_='unique')
    op.drop_column('icon_metadata', 'full_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('icon_metadata', sa.Column('full_key', sa.VARCHAR(length=355), autoincrement=False, nullable=False, comment="Computed: pack.name + ':' + key"))
    op.create_unique_constraint(op.f('uq_icon_full_key'), 'icon_metadata', ['full_key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_icon_metadata_full_key'), 'icon_metadata', ['full_key'], unique=False)
    op.alter_column('github_sync_history', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('github_sync_history', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_github_repository_selections_id'), table_name='github_repository_selections')
    op.alter_column('github_repository_selections', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('github_repository_selections', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
