"""Add GitHub integration models

Revision ID: 86770e62ceb7
Revises: e8ff44c7c77d
Create Date: 2025-08-27 03:20:53.228154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86770e62ceb7'
down_revision: Union[str, Sequence[str], None] = 'e8ff44c7c77d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('github_repository_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('github_file_path', sa.String(length=512), nullable=True))
    op.add_column('documents', sa.Column('github_sha', sa.String(length=40), nullable=True))
    op.add_column('documents', sa.Column('github_sync_status', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('last_github_sync_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_documents_github_repository_id'), 'documents', ['github_repository_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'github_repositories', ['github_repository_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_github_repository_id'), table_name='documents')
    op.drop_column('documents', 'last_github_sync_at')
    op.drop_column('documents', 'github_sync_status')
    op.drop_column('documents', 'github_sha')
    op.drop_column('documents', 'github_file_path')
    op.drop_column('documents', 'github_repository_id')
    # ### end Alembic commands ###
