"""Add custom dictionary table

Revision ID: 8821a39ebdc7
Revises: 2a1b3c4d5e6f
Create Date: 2025-07-24 23:52:40.990868

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8821a39ebdc7"
down_revision: Union[str, Sequence[str], None] = "2a1b3c4d5e6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custom_dictionaries",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("word", sa.String(length=100), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_custom_dictionaries_id"), "custom_dictionaries", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_custom_dictionaries_user_id"),
        "custom_dictionaries",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_custom_dictionaries_user_id"), table_name="custom_dictionaries"
    )
    op.drop_index(op.f("ix_custom_dictionaries_id"), table_name="custom_dictionaries")
    op.drop_table("custom_dictionaries")
    # ### end Alembic commands ###
