"""Initial migration

Revision ID: 8c240984c488
Revises:
Create Date: 2025-07-03 10:36:50.584517

"""
# revision identifiers, used by Alembic.
# revision identifiers, used by Alembic.
revision = "8c240984c488"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
