"""Remove content field and add filesystem storage fields

Revision ID: eca1483c944a
Revises: 857f921cccd9
Create Date: 2025-09-15 04:27:39.549409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eca1483c944a'
down_revision: Union[str, Sequence[str], None] = '857f921cccd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add new columns first
    op.add_column('documents', sa.Column('file_path', sa.String(length=512), nullable=True, comment='Relative path to the file within the storage system'))
    op.add_column('documents', sa.Column('repository_type', sa.String(length=50), nullable=True, comment="Type of repository: 'local', 'github', or 'external'"))

    # Set default values for existing records
    op.execute("UPDATE documents SET repository_type = 'local' WHERE repository_type IS NULL")

    # Now make repository_type NOT NULL
    op.alter_column('documents', 'repository_type', nullable=False)

    # Create indexes
    op.create_index(op.f('ix_documents_file_path'), 'documents', ['file_path'], unique=False)
    op.create_index(op.f('ix_documents_repository_type'), 'documents', ['repository_type'], unique=False)

    # Remove content column
    op.drop_column('documents', 'content')
    op.alter_column('github_accounts', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('github_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('github_accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_github_accounts_id'), 'github_accounts', ['id'], unique=False)
    op.alter_column('github_repositories', 'default_branch',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('github_repositories', 'is_private',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('github_repositories', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('github_repositories', 'auto_sync_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('github_repositories', 'sync_interval_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('github_repositories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('github_repositories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_github_repositories_id'), 'github_repositories', ['id'], unique=False)
    op.alter_column('github_sync_history', 'branch_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('github_sync_history', 'files_changed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('github_sync_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('github_sync_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_github_sync_history_id'), 'github_sync_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_sync_history_id'), table_name='github_sync_history')
    op.alter_column('github_sync_history', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('github_sync_history', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('github_sync_history', 'files_changed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('github_sync_history', 'branch_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_github_repositories_id'), table_name='github_repositories')
    op.alter_column('github_repositories', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('github_repositories', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('github_repositories', 'sync_interval_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('github_repositories', 'auto_sync_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('github_repositories', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('github_repositories', 'is_private',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('github_repositories', 'default_branch',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_github_accounts_id'), table_name='github_accounts')
    op.alter_column('github_accounts', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('github_accounts', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('github_accounts', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('documents', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_documents_repository_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_path'), table_name='documents')
    op.drop_column('documents', 'repository_type')
    op.drop_column('documents', 'file_path')
    # ### end Alembic commands ###
