"""Add enabled field to markdown_lint_rules

Revision ID: f6f4e8618f60
Revises: 5417dceecb6e
Create Date: 2025-09-18 12:30:50.290606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6f4e8618f60'
down_revision: Union[str, Sequence[str], None] = '5417dceecb6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add the column as nullable first to avoid constraint violations
    op.add_column('markdown_lint_rules', sa.Column('enabled', sa.Boolean(), nullable=True))

    # Set default value for existing rows (enable linting by default)
    op.execute("UPDATE markdown_lint_rules SET enabled = true WHERE enabled IS NULL")

    # Make the column non-nullable now that all rows have values
    op.alter_column('markdown_lint_rules', 'enabled', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markdown_lint_rules', 'enabled')
    # ### end Alembic commands ###
